### ISSUE TITLE
Исправление получения токена в документации 

### ISSUE THREAD

**Issue by eremeyko** [feschenko/spotify-to-vk#7]
В документации описано получение токена от приложения Kate Mobile, но при попытке работы с ним выдает ошибку со стороны VK Api:
> vk_api.exceptions.ApiError: [25] Token confirmation required

С токеном от VK Me такой ошибки не возникает. Было бы прекрасно увидеть поправку, чтобы у других не возникло таких проблем 😄

**Comment by feschenko** [comment]
Привет. Спасибо за issue. И правда, вк перестал принимать токен от кейта.
>  Было бы прекрасно увидеть поправку, чтобы у других не возникло таких проблем
В следующий раз можешь смело кидать пулл реквест, я его приму :)
